package model;

import java.util.ArrayList;
import java.util.List;

public class Carrello {

    private String emailUtente;

    private String idProdotto = "";
    private String nomeProdotto;
    private int quantita;
    private float prezzo;



    public Carrello(String emailUtente, String idProdotto, String nomeProdotto, int quantita, float prezzo) {
        this.emailUtente = emailUtente;
        this.idProdotto = idProdotto;
        this.nomeProdotto = nomeProdotto;
        this.quantita = quantita;
        this.prezzo = prezzo;
    }

    public Carrello(String emailUtente) {
        this.emailUtente = emailUtente;
    }

    public Carrello()
    {

    }

    public String getNomeProdotto() {
        return nomeProdotto;
    }

    public void setNomeProdotto(String nomeProdotto) {
        this.nomeProdotto = nomeProdotto;
    }

    public String getEmailUtente() {
        return emailUtente;
    }

    public void setEmailUtente(String emailUtente) {
        this.emailUtente = emailUtente;
    }




    public String getIdProdotto() {
        return idProdotto;
    }

    public void setIdProdotto(String idProdotto) {
        this.idProdotto = idProdotto;
    }

    public int getQuantita() {
        return quantita;
    }

    public void setQuantita(int quantita) {
        this.quantita = quantita;
    }

    public float getPrezzo() {
        return prezzo;
    }

    public void setPrezzo(float prezzo) {
        this.prezzo = prezzo;
    }



    //Auto-generated by Intellij
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Carrello)) return false;

        Carrello carrello = (Carrello) o;

        if (getQuantita() != carrello.getQuantita()) return false;
        if (Float.compare(getPrezzo(), carrello.getPrezzo()) != 0) return false;
        if (getEmailUtente() != null ? !getEmailUtente().equals(carrello.getEmailUtente()) : carrello.getEmailUtente() != null)
            return false;
        if (getIdProdotto() != null ? !getIdProdotto().equals(carrello.getIdProdotto()) : carrello.getIdProdotto() != null)
            return false;
        return getNomeProdotto() != null ? getNomeProdotto().equals(carrello.getNomeProdotto()) : carrello.getNomeProdotto() == null;
    }

    //Auto-generated by Intellij
    @Override
    public int hashCode() {
        int result = getEmailUtente() != null ? getEmailUtente().hashCode() : 0;
        result = 31 * result + (getIdProdotto() != null ? getIdProdotto().hashCode() : 0);
        result = 31 * result + (getNomeProdotto() != null ? getNomeProdotto().hashCode() : 0);
        result = 31 * result + getQuantita();
        result = 31 * result + (getPrezzo() != 0.0f ? Float.floatToIntBits(getPrezzo()) : 0);
        return result;
    }

}


